### ISSUE TITLE
Is "When power_of_2?" intentionally showing up in Antorra view of hstatus

### ISSUE THREAD

**Issue by james-ball-qualcomm** [riscv-software-src/riscv-unified-db#129]
![image](https://github.com/user-attachments/assets/dde3a1cb-82a4-4307-bf86-929c83a57354)

**Comment by dhower-qc** [comment]
Good catch. No, it really shouldn't. This used to be true because the VGEIN field was defined to only be as big as needed to hold the highest guest interrupt number; so, when the number of interrupts (+1) was a power of two, anything could be written into the field. But when it wasn't a power of two, some values would be illegal. We've since switched so that the fields are always as big as defined in the spec, but certain values won't be legal. 

I'll fix this up.

**Comment by dhower-qc** [comment]
fixed in #133
