### ISSUE TITLE
Doubt on definedBy  

### ISSUE THREAD

**Issue by AFOliveira** [riscv-software-src/riscv-unified-db#18]
Hello!
While trying to achieve the automatically generated .yaml filesm I found something that raised a doubt. 

In the following image:
![image](https://github.com/user-attachments/assets/c0dc543d-e679-4134-83fb-61273ffe5fe6)
the instruction andn is "defined by: B and Zbb" although Zbb is a part of "B". Isn't this redundant?

 The problem I find with this when automatic generating it is that on [riscv-opcodes](https://github.com/riscv/riscv-opcodes/blob/master/rv_zbb) , folder name is zbb and so on my approach, it only shows up zbb. I wanted to hear back from you whether you think it is important to have both, since as of now, only zbb is being parsed on this [initial approach](https://github.com/foss-for-synopsys-dwc-arc-processors/riscv-opcodes/tree/SynopsisDescription/yaml_output).

**Comment by dhower-qc** [comment]
As we discussed on the side, the current issue is that if we omit `B` from the above definition, the tool has no way to associate `andn` with the `B` extension. This is because the description of the `B` extension points to `Zbb` (the 'implies' key), but `Zbb` doesn't point back to `B`.

I am going to look at restructuring the schema so that we can determine `Zbb` is a subset of `B`. If we have that, we can omit `B` from definedBy above.
